services:
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    network_mode: "host"
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: 
        PLAINTEXT://192.168.101.3:9092,
        BROKER://localhost:29092,
        CONTROLLER://localhost:9093

      KAFKA_ADVERTISED_LISTENERS: 
        PLAINTEXT://192.168.101.3:9092,
        BROKER://localhost:29092,
        CONTROLLER://localhost:9093

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 
        PLAINTEXT:PLAINTEXT,
        BROKER:PLAINTEXT,
        CONTROLLER:PLAINTEXT
        
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1

      
  schema-registry:
    image: bitnami/schema-registry
    hostname: schema-registry
    container_name: schema-registry
    ports:
      - 8081:8081
      - 8082:8082
    depends_on:
      - broker
    environment:
      SCHEMA_REGISTRY_KAFKA_BROKERS: PLAINTEXT://localhost:29092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      
      